version: "3.9"

services:
  backend:
    build: ./backend/ai-agent
    ports:
      - "8000:8000"
    container_name: medbrief-backend

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    container_name: medbrief-frontend
